import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { ensureSensitivePathsIgnored } from "./gitignore.js";
import { getEnvPath } from "./paths.js";

export interface AppConfig {
  geminiApiKey: string;
  geminiModel: string;
  sourceLang: string;
  targetLang: string;
  projectRoot: string;
}

const KEYS = {
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_MODEL: "GEMINI_MODEL",
  SOURCE_LANG: "SOURCE_LANG",
  TARGET_LANG: "TARGET_LANG",
  PROJECT_ROOT: "PROJECT_ROOT",
} as const;

function parseEnvFile(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function serializeEnv(data: Record<string, string>): string {
  const lines = [
    "# Xcode Translator configuration",
    "# Generated by xcode-translator CLI",
    "",
  ];
  for (const [key, value] of Object.entries(data)) {
    const escaped = value.includes(" ") || value.includes("#") ? `"${value.replace(/"/g, '\\"')}"` : value;
    lines.push(`${key}=${escaped}`);
  }
  lines.push("");
  return lines.join("\n");
}

export function loadConfig(projectRoot: string): Partial<AppConfig> {
  const envPath = getEnvPath(projectRoot);
  if (!existsSync(envPath)) return {};

  const raw = parseEnvFile(readFileSync(envPath, "utf-8"));
  return {
    geminiApiKey: raw[KEYS.GEMINI_API_KEY],
    geminiModel: raw[KEYS.GEMINI_MODEL],
    sourceLang: raw[KEYS.SOURCE_LANG],
    targetLang: raw[KEYS.TARGET_LANG],
    projectRoot: raw[KEYS.PROJECT_ROOT] || projectRoot,
  };
}

export function saveConfig(projectRoot: string, config: Partial<AppConfig>): void {
  const existing = loadConfig(projectRoot);
  const merged: Record<string, string> = {};

  const apiKey = config.geminiApiKey ?? existing.geminiApiKey;
  const model = config.geminiModel ?? existing.geminiModel;
  const sourceLang = config.sourceLang ?? existing.sourceLang;
  const targetLang = config.targetLang ?? existing.targetLang;
  const root = config.projectRoot ?? existing.projectRoot ?? projectRoot;

  if (apiKey) merged[KEYS.GEMINI_API_KEY] = apiKey;
  if (model) merged[KEYS.GEMINI_MODEL] = model;
  if (sourceLang) merged[KEYS.SOURCE_LANG] = sourceLang;
  if (targetLang) merged[KEYS.TARGET_LANG] = targetLang;
  merged[KEYS.PROJECT_ROOT] = root;

  writeFileSync(getEnvPath(projectRoot), serializeEnv(merged), "utf-8");
  ensureSensitivePathsIgnored(projectRoot);
}

export function isConfigComplete(config: Partial<AppConfig>): config is AppConfig {
  return !!(
    config.geminiApiKey &&
    config.geminiModel &&
    config.sourceLang &&
    config.targetLang &&
    config.projectRoot
  );
}

export function getMissingFields(config: Partial<AppConfig>): string[] {
  const missing: string[] = [];
  if (!config.geminiApiKey) missing.push("GEMINI_API_KEY");
  if (!config.geminiModel) missing.push("GEMINI_MODEL");
  if (!config.sourceLang) missing.push("SOURCE_LANG");
  if (!config.targetLang) missing.push("TARGET_LANG");
  return missing;
}
